version: '3.8'

services:
  inventario-app:
    container_name: inventario-app
    build:
      context: ./inventario
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    env_file:
      - stack.env
    restart: unless-stopped
    networks:
      - springnet

networks:
  springnet:
    driver: bridge
