version: '3.8'

services:
  otel-collector:
    image: otel/opentelemetry-collector-contrib:0.110.0
    container_name: otel-collector
    command: ["--config=/etc/otel-collector-config.yaml"]
    volumes:
      - ./static:/etc
    ports:
      - "4317:4317"
      - "4318:4318"
      - "8888:8888"
    networks:
      - otel-net
    depends_on:
      - jaeger
      - loki

  jaeger:
    container_name: jaeger
    image: jaegertracing/all-in-one:1.46
    restart: always
    ports:
      - "16686:16686"
    environment:
      - COLLECTOR_OTLP_ENABLED=true
    networks:
      - otel-net

  inventario-app-test:
    container_name: inventario-app-test
    build:
      context: ./inventario
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    env_file:
      - stack.env
    restart: unless-stopped
    networks:
      - otel-net
    depends_on:
      - otel-collector
      - jaeger

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    volumes:
      - ./static:/etc/prometheus
    ports:
      - "9090:9090"
    networks:
      - otel-net
    depends_on:
      - otel-collector

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - "3000:3000"
    networks:
      - otel-net
    depends_on:
      - prometheus

  loki:
    image: grafana/loki:2.9.8
    container_name: loki
    command: -config.file=/etc/loki/local-config.yaml
    ports:
      - "3100:3100"
    networks:
      - otel-net

networks:
  otel-net:
    driver: bridge
