#server.port: 8081

#Configuration JWT
jwt.secret: ${JWT_SECRET:MySuperSecureJwtSecretKeyOf32CharsOrMore!}

cors:
  allowed-origins: ${CORS_ALLOWED_ORIGINS:http://localhost:*}

spring:
  application:
    name: inventario

  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: none #default: none
    properties:
      # Hibernate core
      hibernate.jdbc.time_zone: UTC
      hibernate.lob.non_contextual_creation: true
      hibernate.format_sql: true

      # Envers — match your lowercase tables/suffix
      hibernate.envers.audit_table_suffix: _aud
      hibernate.envers.revision_table_name: revinfo
      hibernate.envers.revision_field_name: rev
      hibernate.envers.revision_timestamp_field_name: revtstmp

      # You created *_mod columns; enable modified flags
      hibernate.envers.global_with_modified_flag: true
      hibernate.envers.with_modified_flag_suffix: _mod

      # Optional but handy: keep full row on delete
      hibernate.envers.store_data_at_delete: true

  # Flyway settings
  flyway:
    enabled: true #default: true
    locations: classpath:db/migration

  datasource:
    url: jdbc:mysql://${MYSQL_HOST:127.0.0.1}:${MYSQL_PORT:3306}/${MYSQL_DB:inventariodb}
    username: ${MYSQL_USER:user}
    password: ${MYSQL_PASSWORD:12345678}
    driver-class-name: com.mysql.cj.jdbc.Driver

  h2:
    console:
      enabled: false

  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}
      username: ${REDIS_USERNAME:}
      password: ${REDIS_PASSWORD:}

---
spring:
  application:
    name: inventario

  config:
    activate:
      on-profile: dev

  flyway:
    enabled: true
    locations: classpath:db/migration

  jpa:
    hibernate:
      ddl-auto: none
    #show-sql: true

  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}
      username: ${REDIS_USERNAME:}
      password: ${REDIS_PASSWORD:}

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    # URL, username, password will be overridden by Testcontainers

#  logging:
#    level:
#      org.hibernate.SQL: DEBUG
#      org.hibernate.orm.jdbc.bind: TRACE
#      org.springframework.transaction: DEBUG

  # avoid session deserialization headaches in dev
  server:
    servlet:
      session:
        persistent: false







