name: Qodana (Community)
on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - dev

jobs:
  qodana:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
      checks: write

    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.event_name == 'pull_request' && github.event.pull_request.head.sha || '' }}
          fetch-depth: 0

      - name: Qodana Scan (Community)
        uses: JetBrains/qodana-action@v2025.1
        with:
          args: --linter=jetbrains/qodana-jvm-community:2025.1

      - name: Upload Qodana results
        uses: actions/upload-artifact@v4
        with:
          name: qodana-results
          path: ${{ runner.temp }}/qodana/results
          if-no-files-found: warn
