name: Qodana
on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - dev
      - 'releases/*'

jobs:
  qodana:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
      checks: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.sha }}
          fetch-depth: 0

      - name: Qodana Scan
        uses: JetBrains/qodana-action@v2025.2
        with:
          # Store results in a temp dir and auto-upload as an artifact
          results-dir: ${{ runner.temp }}/qodana/results
          upload-result: true
          artifact-name: qodana-report
          # Pass CLI flags via args (no working-directory input in 2025.2)
          args: >
            --project-dir ./inventario
            --save-report
        env:
          QODANA_TOKEN: ${{ secrets.QODANA_TOKEN_2110364401 }}
          QODANA_ENDPOINT: 'https://qodana.cloud'
