name: Qodana Test
on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - dev
      - main
      - 'releases/*'

jobs:
  qodana:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
      checks: write
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.sha }}
          fetch-depth: 0

      - name: Qodana Scan
        uses: JetBrains/qodana-action@v2025.2
        with:
          args: --project-dir=./inventario --image=jetbrains/qodana-jvm-community:2025.2
          results-dir: ${{ runner.temp }}/qodana/results
          upload-result: false
        env:
          #QODANA_TOKEN: ${{ secrets.QODANA_TOKEN_2110364401 }}
          #QODANA_ENDPOINT: 'https://qodana.cloud'

      - name: Upload Qodana HTML report
        uses: actions/upload-artifact@v4
        with:
          name: qodana-html
          path: ${{ runner.temp }}/qodana/results/report/
