name: Quality & Security (Qodana + Snyk + ZAP)

on:
  push:
    branches: [ dev ]
  pull_request:
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read
  security-events: write
  actions: read   # helpful for some SARIF uploads in private repos

jobs:
  qodana:
    runs-on: ubuntu-latest
    timeout-minutes: 20
    environment: enviroments
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.sha || github.sha }}
          fetch-depth: 0

      # Qodana uses CLI args; point it at the subfolder project
      - name: Qodana Scan (Cloud if token, else Community)
        uses: JetBrains/qodana-action@v2025.1
        env:
          QODANA_TOKEN: ${{ secrets.QODANA_TOKEN }}
        with:
          # keep it single-line so nothing gets dropped by YAML folding
          args: "--project-dir=inventario --results-dir=qodana/results ${{ secrets.QODANA_TOKEN == '' && '--linter=jetbrains/qodana-jvm-community:2025.1' || '' }}"

      # Upload Qodana SARIF to GitHub Security tab (code scanning)
      - name: Upload Qodana SARIF to Security tab
        if: always()
        uses: github/codeql-action/upload-sarif@v3
        with:
          # Qodana writes SARIF here by default under results dir
          sarif_file: qodana/results/qodana.sarif.json

      - name: Upload Qodana HTML
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: qodana-report
          path: qodana/results/report/
          if-no-files-found: warn

      - name: Upload Qodana logs
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: qodana-logs
          path: qodana/results/logs/
          if-no-files-found: warn

  snyk:
    runs-on: ubuntu-latest
    timeout-minutes: 20
    environment: enviroments
    defaults:
      run:
        working-directory: inventario
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '21'
          cache: gradle

      - name: Make Gradle wrapper executable
        run: chmod +x ./gradlew

      - name: Build (no tests)
        run: ./gradlew --no-daemon build -x test

      - name: Run Snyk (Gradle)
        uses: snyk/actions/gradle@master
        continue-on-error: true   # per Snyk docs, so upload step still runs
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        with:
          args: --severity-threshold=high --sarif-file-output=snyk.sarif

      - name: Upload Snyk SARIF to Security tab
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: inventario/snyk.sarif

      - name: Upload Snyk file (artifact)
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: snyk-sarif
          path: inventario/snyk.sarif
          if-no-files-found: warn

  zap:
    runs-on: ubuntu-latest
    timeout-minutes: 25
    needs: [qodana, snyk]

    # env:
    #   SPRING_PROFILES_ACTIVE: dev
    #   SPRING_DATASOURCE_URL: jdbc:mysql://127.0.0.1:3306/inventariodb?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
    #   SPRING_DATASOURCE_USERNAME: user
    #   SPRING_DATASOURCE_PASSWORD: 12345678

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '21'
          cache: gradle

      - name: Make Gradle wrapper executable
        working-directory: inventario
        run: chmod +x ./gradlew

      - name: Build app (no tests)
        working-directory: inventario
        run: ./gradlew --no-daemon build -x test

      - name: Start app and run OWASP ZAP Full Scan
        run: |
          nohup java -jar inventario/build/libs/*.jar > app.log 2>&1 &
          echo "Waiting for app..."
          for i in {1..40}; do
            if curl -sSf http://127.0.0.1:8080 >/dev/null; then
              echo "App is up!"
              break
            fi
            sleep 3
          done

          if ! curl -sSf http://127.0.0.1:8080 >/dev/null; then
            echo "App did not start in time" >&2
            exit 1
          fi

          docker run --rm \
            -v "$(pwd)":/zap/wrk/:rw \
            --network="host" \
            zaproxy/zap-stable \
            zap-full-scan.py \
            -t http://127.0.0.1:8080 \
            -r zap_full_report.html || true

      - name: Upload ZAP Report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: zap-report
          path: zap_full_report.html
          if-no-files-found: error

      - name: Upload app logs
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: app-log
          path: app.log
          if-no-files-found: warn
