name: CI (JUnit + Cucumber + Playwright + JaCoCo)

on:
  push:
    branches: [ main ]
  pull_request:
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  tests:
    runs-on: ubuntu-latest
    timeout-minutes: 45

    defaults:
      run:
        working-directory: inventario

    env:
      HEADLESS: true
      SPRING_PROFILES_ACTIVE: dev
      SPRING_DATASOURCE_URL: jdbc:mysql://127.0.0.1:3306/inventariodb?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
      SPRING_DATASOURCE_USERNAME: user
      SPRING_DATASOURCE_PASSWORD: 12345678

      # Playwright Java can download browsers automatically on first run
      # PLAYWRIGHT_BROWSERS_PATH: 0  # (optional) keep browsers in project dir

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '21'
          cache: gradle

      # Install playwright dependencies
      - name: Install system deps (optional, for Playwright headless)
        run: |
          sudo apt-get update
          sudo apt-get install -y libnss3 libxss1 libasound2 fonts-liberation > /dev/null

      # Bring up MySQL using the compose file under src/test/java
      - name: Start MySQL (docker compose)
        working-directory: inventario/src/test/java
        run: docker compose up -d

      - name: Wait for MySQL to be ready
        run: |
          sudo apt-get update && sudo apt-get install -y mysql-client > /dev/null
          for i in {1..60}; do
            if mysqladmin ping -h 127.0.0.1 -u"${SPRING_DATASOURCE_USERNAME}" -p"${SPRING_DATASOURCE_PASSWORD}" --silent; then
              echo "MySQL is up"; break
            fi
            echo "Waiting for MySQL... ($i)"
            sleep 2
          done

      # ---- Run subsets for clarity/logs ---------------------------------

      - name: JUnit subset (service/security)
        working-directory: inventario
        run: |
          chmod +x ./gradlew
          ./gradlew --no-daemon test \
            --tests "org.example.inventario.security.*" \
            --tests "org.example.inventario.services.inventario.*"

      - name: Cucumber subset
        working-directory: inventario
        run: |
          ./gradlew --no-daemon test \
            --tests "org.example.inventario.CucumberTest"

      - name: Playwright subset
        working-directory: inventario
        run: |
          # Pass property so Playwright Java downloads browsers on first run (faster on retries)
          ./gradlew --no-daemon -Dplaywright.cli.install=true test \
            --tests "org.example.inventario.playwright.*"

      # ---- One consolidated run for complete coverage -------------------

      - name: Clean + all tests + JaCoCo
        working-directory: inventario
        run: |
          ./gradlew --no-daemon clean test jacocoTestReport -Dplaywright.cli.install=true

      # ---- Artifacts ----------------------------------------------------

      - name: Upload JUnit & Cucumber test reports
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: junit-cucumber-reports
          path: |
            inventario/build/reports/tests/test
            inventario/target/cucumber-reports.html
          if-no-files-found: warn

      - name: Upload Playwright logs (if any)
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: playwright-output
          path: |
            inventario/build/test-results/test
            inventario/build/reports/tests/test
          if-no-files-found: warn

      - name: Upload JaCoCo HTML
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: jacoco-html
          path: inventario/build/jacocoHtml
          if-no-files-found: error

      # Stop compose (nice cleanup)
      - name: Stop MySQL (docker compose)
        if: always()
        working-directory: inventario/src/test/java
        run: docker compose down -v
